// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/enum.go

package types

import (
	"fmt"
	"go/token"
)

// Enum describes the closed variants of a named enum. Its backing storage uses
// typed fields, so ordinary Go pointer maps, copies and write barriers apply.
// Backing fields are implementation details and are not source-level payloads.
type Enum struct {
	variants     []*EnumVariant
	defaultIndex int
}

// EnumVariant describes one unit, positional or record alternative.
type EnumVariant struct {
	name    string
	pkg     *Package
	tag     int
	record  bool
	fields  []*Var
	storage int
	obj     Object
	origin  Object // declaration object retained by instantiated descriptors
}

func (e *Enum) NumVariants() int           { return len(e.variants) }
func (e *Enum) Variant(i int) *EnumVariant { return e.variants[i] }
func (e *Enum) Default() *EnumVariant      { return e.variants[e.defaultIndex] }
func (e *Enum) Lookup(name string, pkg *Package) *EnumVariant {
	for _, v := range e.variants {
		if v.name == name && (v.pkg == pkg || isExported(name)) {
			return v
		}
	}
	return nil
}
func (v *EnumVariant) Object() Object    { return v.obj }
func (v *EnumVariant) Name() string      { return v.name }
func (v *EnumVariant) Pkg() *Package     { return v.pkg }
func (v *EnumVariant) Tag() int          { return v.tag }
func (v *EnumVariant) IsRecord() bool    { return v.record }
func (v *EnumVariant) NumFields() int    { return len(v.fields) }
func (v *EnumVariant) Field(i int) *Var  { return v.fields[i] }
func (v *EnumVariant) StorageIndex() int { return v.storage }

// EnumOf returns the enum description of t, or nil for an ordinary Go type.
func EnumOf(t Type) *Enum {
	if t == nil {
		return nil
	}
	t = Unalias(t)
	s, ok := t.Underlying().(*Struct)
	if !ok || s.enum == nil {
		return nil
	}
	n, named := t.(*Named)
	if !named {
		return s.enum
	}
	n.mu.Lock()
	defer n.mu.Unlock()
	if n.enumCache == nil {
		n.enumCache = cloneEnum(s.enum, s)
		bindEnumOwner(n.enumCache, n)
	}
	return n.enumCache
}

func bindEnumOwner(e *Enum, owner Type) {
	for _, v := range e.variants {
		pos := nopos
		if v.obj != nil {
			pos = v.obj.Pos()
		}
		if !v.record && len(v.fields) != 0 {
			params := make([]*Var, len(v.fields))
			for i, f := range v.fields {
				params[i] = NewParam(f.pos, f.pkg, "", f.typ)
			}
			sig := NewSignatureType(nil, nil, nil, NewTuple(params...), NewTuple(NewParam(pos, v.pkg, "", owner)), false)
			f := NewFunc(pos, v.pkg, v.name, sig)
			if origin, ok := v.origin.(*Func); ok {
				f.origin = origin.Origin()
			}
			v.obj = f
		} else {
			f := NewVar(pos, v.pkg, v.name, owner)
			if origin, ok := v.origin.(*Var); ok {
				f.origin = origin.Origin()
			}
			v.obj = f
		}
	}
}

func cloneEnum(desc *Enum, backing *Struct) *Enum {
	if desc == nil {
		return nil
	}
	e := &Enum{defaultIndex: desc.defaultIndex}
	for _, v := range desc.variants {
		copy := *v
		copy.origin = v.obj
		copy.fields = make([]*Var, len(v.fields))
		payload := backing.fields[v.storage].typ.(*Struct)
		for j, f := range v.fields {
			p := *f
			p.typ = payload.fields[j].typ
			p.origin = f.Origin()
			copy.fields[j] = &p
		}
		e.variants = append(e.variants, &copy)
	}
	return e
}

// NewEnumVariant creates a declaration descriptor for an enum payload.
// Fields are copied, preserving the Go type and visibility of each payload.
func NewEnumVariant(name string, pkg *Package, fields []*Var, record bool) *EnumVariant {
	return NewEnumVariantAt(nopos, pkg, name, fields, record)
}

// NewEnumVariantAt creates a variant descriptor at its declaration position.
func NewEnumVariantAt(pos token.Pos, pkg *Package, name string, fields []*Var, record bool) *EnumVariant {
	return &EnumVariant{name: name, pkg: pkg, fields: append([]*Var(nil), fields...), record: record, obj: NewVar(pos, pkg, name, Typ[Invalid])}
}

// NewEnum creates typed backing storage for a closed set of alternatives.
// The default variant's tag is zero independently of its declaration order.
func NewEnum(variants []*EnumVariant, defaultIndex int) *Struct {
	if defaultIndex < 0 || defaultIndex >= len(variants) {
		panic("invalid default enum variant")
	}
	e := &Enum{defaultIndex: defaultIndex}
	st := &Struct{enum: e, fields: []*Var{NewField(nopos, nil, "$gonTag", Typ[Uint], false)}}
	next := 1
	for i, v := range variants {
		copy := *v
		copy.storage = i + 1
		if i == defaultIndex {
			copy.tag = 0
		} else {
			copy.tag = next
			next++
		}
		backing := make([]*Var, len(copy.fields))
		for j, f := range copy.fields {
			backing[j] = NewField(f.pos, f.pkg, fmt.Sprintf("$gonPayload%d", j), f.typ, false)
		}
		st.fields = append(st.fields, NewField(nopos, copy.pkg, fmt.Sprintf("$gonVariant%d", i), NewStruct(backing, nil), false))
		e.variants = append(e.variants, &copy)
	}
	st.markComplete()
	return st
}

var canonicalResult *Named
var migrationOption *Alias

// migrationOptionalEnum is a temporary descriptor for retired source syntax.
// It never becomes the public identity or metadata of the native optional.
func (check *Checker) sourceEnum(t Type) *Enum {
	if check.conf.MigrateOptionals {
		if o := OptionalOf(t); o != nil {
			st := NewEnum([]*EnumVariant{NewEnumVariant("None", nil, nil, false), NewEnumVariant("Some", nil, []*Var{NewField(nopos, nil, "", o.Elem(), false)}, false)}, 0)
			bindEnumOwner(st.enum, t)
			return st.enum
		}
	}
	return EnumOf(t)
}

// IsCanonicalResult recognizes the predeclared Result identity and aliases.
func IsCanonicalResult(t Type) bool {
	if t == nil {
		return false
	}
	n, ok := Unalias(t).(*Named)
	return ok && n.Origin() == canonicalResult
}

func defPredeclaredEnums() {
	param := NewTypeParam(NewTypeName(nopos, nil, "T", nil), &emptyInterface)
	aliasObj := NewTypeName(nopos, nil, "Option", nil)
	aliasObj.setParent(Universe)
	migrationOption = NewAlias(aliasObj, NewOptional(param))
	migrationOption.SetTypeParams([]*TypeParam{param})

	obj := NewTypeName(nopos, nil, "Result", nil)
	named := NewNamed(obj, nil, nil)
	params := []*TypeParam{
		NewTypeParam(NewTypeName(nopos, nil, "T", nil), &emptyInterface),
		NewTypeParam(NewTypeName(nopos, nil, "E", nil), &emptyInterface),
	}
	named.SetTypeParams(params)
	st := NewEnum([]*EnumVariant{
		NewEnumVariant("Ok", nil, []*Var{NewField(nopos, nil, "", params[0], false)}, false),
		NewEnumVariant("Err", nil, []*Var{NewField(nopos, nil, "", params[1], false)}, false),
	}, 0)
	named.SetUnderlying(st)
	for _, v := range st.enum.variants {
		v.obj = NewVar(nopos, nil, v.name, named)
	}
	if Universe.Insert(obj) != nil {
		panic("duplicate canonical Result")
	}
	canonicalResult = named
}
