// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/optioncontext.go

// Copyright 2026 The Gon Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package types

import (
	"go/ast"
	. "internal/types/errors"
)

// isOptionContextExpr finds constructs whose type must be supplied before
// their children are checked. Calls establish their own argument contexts.
func isOptionContextExpr(e ast.Expr) bool {
	switch e := e.(type) {
	case *ast.ContextualVariantExpr:
		return true
	case *ast.ParenExpr:
		return isOptionContextExpr(e.X)
	case *ast.CondExpr:
		return isOptionContextExpr(e.Then) || isOptionContextExpr(e.Else)
	case *ast.MatchExpr:
		for _, arm := range e.Arms {
			if isOptionContextExpr(arm.Value) {
				return true
			}
		}
	}
	return false
}

// A contextual constructor (or an implicitly lifted Option result) needs
// a complete lambda result target; its body cannot infer that target.
func lambdaNeedsOptionContext(e *ast.LambdaExpr, sig *Signature) bool {
	return isOptionContextExpr(e.Body) || sig.results.Len() == 1 && IsOptional(sig.results.At(0).typ)
}

func (check *Checker) contextualVariant(T *target, x *operand, e *ast.ContextualVariantExpr) {
	x.expr = e
	fail := func(message string) {
		check.error(e, InvalidCall, message)
		x.invalidate()
		check.use(e.Args...)
	}
	if T == nil || T.kind == inferTarget || !(IsCanonicalResult(T.typ) || check.conf.MigrateOptionals && IsOptional(T.typ)) || isGeneric(T.typ) {
		fail("contextual constructor requires a fully known canonical Result type")
		return
	}
	v := check.sourceEnum(T.typ).Lookup(e.Name.Name, check.pkg)
	if v == nil {
		fail("contextual constructor does not belong to the expected canonical type")
		return
	}
	check.recordUse(e.Name, v.Object())
	if v.NumFields() == 0 {
		if e.Lparen.IsValid() || len(e.Args) != 0 {
			fail("contextual None is a value and does not accept arguments")
			return
		}
	} else {
		if !e.Lparen.IsValid() || len(e.Args) != 1 {
			fail("contextual constructor requires exactly one payload argument")
			return
		}
		var arg operand
		payload := v.Field(0).Type()
		check.expr(newTarget(payload, "contextual constructor payload"), &arg, e.Args[0])
		check.assignment(&arg, payload, "contextual constructor payload")
		if !arg.isValid() {
			x.invalidate()
			return
		}
	}
	x.mode_, x.typ_ = value, T.typ
}

// optionAssignment performs one implicit lift without changing the recorded
// source type. Its recursive assignment checks only ordinary assignability of
// the payload; it must never invent another Option layer.
func (check *Checker) optionAssignment(x *operand, T Type, context string) bool {
	if check.optionLiftDepth != 0 || x.multiValue || !IsOptional(T) || isGeneric(T) {
		return false
	}
	if ok, _ := x.assignableTo(check, T, nil); ok {
		return false
	}
	if x.typ() != Typ[UntypedNil] {
		payload := canonicalPayload(T, "$present")
		check.optionLiftDepth++
		check.assignment(x, payload, context)
		check.optionLiftDepth--
		if !x.isValid() {
			return true
		}
	}
	if check.OptionalConversions != nil {
		check.OptionalConversions[x.expr] = T
	}
	x.mode_, x.typ_, x.val = value, T, nil
	return true
}
