// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/patterntest.go

package types

import (
	"go/ast"
	"go/token"
	. "internal/types/errors"
)

// conditionPatternTests permits only tests that form the condition itself or
// are leaves in its top-level && chain. Other expressions introduce no binds.
func conditionPatternTests(condition ast.Expr) map[*ast.PatternTestExpr]bool {
	permitted := make(map[*ast.PatternTestExpr]bool)
	var walk func(ast.Expr)
	walk = func(expression ast.Expr) {
		switch expression := ast.Unparen(expression).(type) {
		case *ast.PatternTestExpr:
			permitted[expression] = true
		case *ast.BinaryExpr:
			if expression.Op == token.LAND && expression.Y != nil {
				walk(expression.X)
				walk(expression.Y)
			}
		}
	}
	walk(condition)
	return permitted
}

func (check *Checker) patternTestExpr(x *operand, e *ast.PatternTestExpr) {
	var subject operand
	check.expr(nil, &subject, e.X)
	if subject.isValid() {
		check.assignment(&subject, nil, "pattern test operand")
	}
	var bindings []matchBinding
	coverage := check.matchPattern(e.Pattern, subject.typ(), false, &bindings)
	if subject.isValid() {
		budget := 10000
		if matchUseful([][]*matchCoverage{{coverage}}, []*matchCoverage{{wild: true}}, []Type{subject.typ()}, &budget) == nil {
			check.error(e.Pattern, InvalidMatch, "pattern test must not use a pattern that always matches")
		}
	}
	if len(bindings) != 0 && !check.patternTestContexts[e] {
		check.error(e.Pattern, InvalidMatch, "pattern test bindings require an if condition or a top-level && operand of that condition")
	} else {
		for _, binding := range bindings {
			obj := newVar(LocalVar, binding.name.Pos(), check.pkg, binding.name.Name, binding.typ)
			check.declare(check.scope, binding.name, obj, e.End())
		}
	}
	x.expr, x.mode_, x.typ_ = e, value, Typ[UntypedBool]
	if !subject.isValid() {
		x.invalidate()
	}
	check.hasCallOrRecv = true
}

func (check *Checker) openPatternScope(condition ast.Expr, body ast.Node) {
	scope := NewScope(check.scope, condition.Pos(), body.End(), "if pattern bindings")
	check.recordScope(condition, scope)
	check.scope = scope
}
