// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/stringenum.go

// Copyright 2026 The Gon Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package types

import (
	. "internal/types/errors"
	"slices"
)

// bindStringEnumParse gives each concrete enum descriptor its own static
// parser. It is a function, rather than a method expression with a receiver.
func bindStringEnumParse(e *Enum, owner Type) {
	if !e.IsString() || e.NumVariants() == 0 || e.defaultIndex < 0 {
		return
	}
	obj := e.Default().Object()
	pos, pkg := obj.Pos(), obj.Pkg()
	if named, ok := Unalias(owner).(*Named); ok {
		pos, pkg = named.Obj().Pos(), named.Obj().Pkg()
	}
	sig := NewSignatureType(nil, nil, nil,
		NewTuple(NewParam(pos, pkg, "text", Typ[String])),
		NewTuple(NewParam(pos, pkg, "", owner)), false)
	e.parse = NewFunc(pos, pkg, "Parse", sig)
}

// declaredUnderlying returns the underlying type of the just declared type
// named, or nil if it cannot be determined yet. It never forces an incomplete
// declaration: package-level types may refer to each other in a cycle that is
// valid because it passes through a type literal, as in
//
//	type A B
//	type B *A
//
// When B is declared first, the declaration of A completes while B's
// right-hand side is still unset, and Named.Underlying must not be called
// for A. A string enum has no such dependency (its payloads are strings), so
// a chain that ends in an incomplete declaration never denotes one.
func declaredUnderlying(named *Named) Type {
	var t Type = named
	var path []*Named // chains are short; a local type may still refer to itself
	for {
		switch x := t.(type) {
		case *Alias:
			if t = unalias(x); t == nil {
				return nil // incomplete alias
			}
		case *Named:
			if x.stateHas(hasUnder) {
				return x.underlying
			}
			if slices.Contains(path, x) {
				return nil // cycle that is diagnosed elsewhere
			}
			path = append(path, x)
			x.unpack()
			if t = x.rhs(); t == nil {
				return nil // declaration in progress
			}
		default:
			return t
		}
	}
}

// addStringEnumMethods installs ordinary, exported methods without introducing
// dependencies on encoding packages or on the spelling of predeclared names.
func (check *Checker) addStringEnumMethods(named *Named) {
	if s, _ := declaredUnderlying(named).(*Struct); s == nil || s.enum == nil || !s.enum.IsString() {
		return
	}
	e := EnumOf(named)
	if e == nil || !e.IsString() {
		return
	}
	for _, method := range check.methods[named.Obj()] {
		if method.Name() == "Parse" {
			check.error(method, DuplicateDecl, "string enum method Parse collides with the automatic parser")
		}
	}
	pos, pkg := named.Obj().Pos(), named.Obj().Pkg()
	param := func(name string, typ Type) *Var { return NewParam(pos, pkg, name, typ) }
	errorType := Universe.Lookup("error").Type()
	add := func(name string, pointer bool, params, results *Tuple) {
		var receiver Type = named
		var rparams []*TypeParam
		if params := named.TypeParams(); params.Len() != 0 {
			rparams = make([]*TypeParam, params.Len())
			args := make([]Type, len(rparams))
			for i := range rparams {
				p := params.At(i)
				rparams[i] = check.newTypeParam(NewTypeName(pos, pkg, p.Obj().Name(), nil), Typ[Invalid])
				args[i] = rparams[i]
				check.mono.recordCanon(rparams[i], p)
			}
			smap := makeRenameMap(params.list(), rparams)
			for i, p := range rparams {
				p.bound = check.subst(pos, params.At(i).bound, smap, nil, check.context())
			}
			receiver = check.instance(pos, named, args, nil, check.context())
		}
		if pointer {
			receiver = NewPointer(receiver)
		}
		sig := NewSignatureType(NewParam(pos, pkg, "value", receiver), rparams, nil, params, results, false)
		named.AddMethod(NewFunc(pos, pkg, name, sig))
	}
	add("String", false, nil, NewTuple(param("", Typ[String])))
	add("MarshalText", false, nil, NewTuple(param("", NewSlice(Typ[Byte])), param("", errorType)))
	add("UnmarshalText", true, NewTuple(param("text", NewSlice(Typ[Byte]))), NewTuple(param("", errorType)))
}
